# Generated by Django 5.0.6 on 2024-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='employee_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='head_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
