# Generated by Django 5.0.6 on 2024-06-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_remove_internshippost_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippost',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
