# Generated by Django 5.0.6 on 2024-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_internshippost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_pic',
            field=models.ImageField(default='images/profile_pics/Default.png', upload_to='images/company_pics'),
        ),
    ]
