# Generated by Django 5.0.6 on 2024-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_alter_companyprofile_user'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshippost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='company',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='job_poster',
        ),
        migrations.AddField(
            model_name='internshippost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post.tag'),
        ),
    ]
