class AppList {
  AppList._();
  static const  List<String> preferenceList = [
    'Python',
    'JavaScript',
    'Java',
    'C++',
    'C#',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'Go',
    'HTML',
    'CSS',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'Django',
    'Flask',
    'Flutter',
    'React Native',
    'Android Development',
    'iOS Development',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'R',
    'SQL',
    'MySQL',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'SQLite',
    'AWS',
    'Azure',
    'Google Cloud Platform',
    'Docker',
    'Kubernetes',
    'Jenkins',
    'Terraform',
    'Ansible',
    'Ethical Hacking',
    'Network Security',
    'Cryptography',
    'Penetration Testing',
    'SIEM',
    'Git',
    'GitHub',
    'Bitbucket',
    'JIRA',
    'Visual Studio Code',
    'IntelliJ IDEA',
    'Blockchain',
    'IoT',
    'AR/VR',
    'Robotics',
    'Game Development',
    'AI',
  ];
  static const List<String> softSkillList = [
    'Communication',
    'Teamwork',
    'Problem-Solving',
    'Time Management',
    'Adaptability',
    'Critical Thinking',
    'Creativity',
    'Emotional Intelligence',
    'Leadership',
    'Conflict Resolution',
    'Decision Making',
    'Negotiation',
    'Stress Management',
    'Empathy',
    'Active Listening',
    'Interpersonal Skills',
    'Networking',
    'Public Speaking',
    'Collaboration',
    'Self-Motivation',
    'Organization',
    'Attention to Detail',
    'Patience',
    'Responsibility',
    'Work Ethic',
    'Positive Attitude',
    'Flexibility',
    'Persuasion',
    'Delegation',
    'Mentoring',
  ];
  static const List<String> companyList = [
    'Google Inc',
    'Apple',
    'Microsoft',
    'Amazon',
    'Facebook'
  ];
}
