// pre-defined style for text

class AppText {
  static final enText = {
    'welcome-title': 'Get the internship of your desires',
    'welcome-body': 'Finding you dream intern job more easy and faster with',
    'welcome-button': 'Let\'s get started',
    'signIn-title': 'Welcome Back!',
    'signIn-text': 'Fill your details or continue with social media ',
    'signIn-button': 'LOGIN',
    'signUp-button': 'REGISTER',
    'signUp_text': 'Don\'t have an account?',
    'forgot-password': 'Forgot Your Password?',
    'appBar-title': 'Welcome, Byun Woo Seok',
    'appBar-subTitle': 'Find your internship program',
    'search-text': 'Find Company, Job, Location',
    'findjob-text': 'Find Job',
    'recommended-text': 'Recommended For You',
    'register_title': 'Rrgister Account',
    'register_text': 'Fill your details or continue with social media',
    'check_email_title': 'Check Your Email',
    'check_email_text':
        'We have sent the reset password to the email address brandonelouis@gmial.com',
    'open_email_button': 'OPEN YOUR EMAIL',
    'back_to_login_button': 'BACK TO LOGIN',
    'success_title': 'Successful',
    'success_text':
        'Your password has been updated, please change your password regularly to avoid this happening',
    'continue_button': 'CONTINUE',
    'verify_title': 'Verification Code',
    'verify_text': 'We have sent the verification code to your email address',
    'job_detail_title': 'Internship Detail',
    'job_title': 'Job Description',
    'job_requirement_title': 'Requirements',
    'job_location_title': 'Location',
    'informations_title': 'Informations',
    'others_title': 'Facilities and Others',
    'cv_title': 'Upload CV',
    'cv_text': 'Add your CV/Resume to apply for a job',
    'company_title': 'About Company',
    'website_title': 'Website',
    'gallery_title': 'Company Gallery',
    'profile_name': 'Byun Woo Seok',
    'profile_email': 'Byunwooseok@gmail.com',
    'profile': 'Profile',
    'setting': 'Setting',
    'warning_title': 'No CV upload yet',
    'warning_text':
        'You don\'t have a CV uploaded yet. Would you like to upload one now?',
    'upload_text_button': 'Upload CV',
    'cancel_text': 'Cancel',
    'success_upload_title': 'Successful',
    'success_upload_text':
        'Your CV has been uploaded successfully. The company will review your application and get back to you soon.',
    'change_pwd': 'Change Password',
    'update_button': 'Update',
    'cancle_button': 'Cancel',
    'description': 'Description',
  };
}
