# Generated by Django 5.0.6 on 2024-06-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0001_initial'),
        ('internship', '0005_internshippost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.companyprofile'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cv_maker.educationlevel'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cv_maker.school'),
        ),
    ]
