# Generated by Django 5.0.6 on 2024-06-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0003_remove_usercompany_company_usercompany_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cv_maker.major'),
        ),
    ]
